version: '3.8'
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./mongodb/database:/data/db
    ports:
    - 27017:27017
    restart: unless-stopped
  web:
    image: "imagesharingservice-img"
    build: .
    ports:
     - "3000:3000"
    volumes:
     - ./:/usr/src
     - ./assets:/images:rw
